### ISSUE TITLE
Caught exception: Error: Redis connection

### ISSUE THREAD

**Issue by jlnslv** [mape/node-express-boilerplate#11]
Hey there,

After a npm install which went smoothly I get the following error on startup. I tried to fix it myself but I can't. Would you mind to help me out please?

info  - socket.io started
Running in development mode @ http://localhost:8080
Caught exception: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/Users/jsilva/Dropbox/Projects/github/scrumpoker/node_modules/connect-redis/node_modules/redis/index.js:136:24)
    at Socket.<anonymous> (/Users/jsilva/Dropbox/Projects/github/scrumpoker/node_modules/connect-redis/node_modules/redis/index.js:70:14)
    at Socket.emit (events.js:67:17)
    at Array.0 (net.js:319:25)
    at EventEmitter._tickCallback (node.js:192:40)

Thanks :D

**Comment by mape** [comment]
Have you verified that you have a working redis server?

```
Caught exception: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED
```

**Comment by jlnslv** [comment]
Hmm... I didn't install it yet. Thought it would come along your boilerplate.

Thank you very much for your quick reply.
