### ISSUE TITLE
Error on startup - Unexpected token: name (GET) (line: 9406, col: 8, pos: 252890)

### ISSUE THREAD

**Issue by haganbt** [mape/node-express-boilerplate#15]
After install, and startup I get the following error:

Caught exception: Unexpected token: name (GET) (line: 9406, col: 8, pos: 252890)

Error
    at new JS_Parse_Error (/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:263:22)
    at js_error (/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:271:15)
    at croak (/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:732:17)
    at token_error (/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:739:17)
    at unexpected (/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:745:17)
    at Object.semicolon [as 1](/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:765:51)
    at prog1 (/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:1313:28)
    at simple_statement (/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:905:35)
    at /Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:813:35
    at /Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:1296:32

**Comment by ayeshasiddika9196** [comment]
reset

**Comment by ayeshasiddika9196** [comment]
[]() expended

**Comment by ayeshasiddika9196** [comment]
> After install, and startup I get the following error:
> 
> Caught exception: Unexpected token: name (GET) (line: 9406, col: 8, pos: 252890)
> 
> Error
>     at new JS_Parse_Error (/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:263:22)
>     at js_error (/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:271:15)
>     at croak (/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:732:17)
>     at token_error (/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:739:17)
>     at unexpected (/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:745:17)
>     at Object.semicolon [as 1](/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:765:51)
>     at prog1 (/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:1313:28)
>     at simple_statement (/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:905:35)
>     at /Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:813:35
>     at /Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:1296:32
> 
inflowing Error

**Comment by ayeshasiddika9196** [comment]
> After install, and startup I get the following error:
> 
> Caught exception: Unexpected token: name (GET) (line: 9406, col: 8, pos: 252890)
> 
> Error
>     at new JS_Parse_Error (/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:263:22)
>     at js_error (/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:271:15)
>     at croak (/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:732:17)
>     at token_error (/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:739:17)
>     at unexpected (/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:745:17)
>     at Object.semicolon [as 1](/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:765:51)
>     at prog1 (/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:1313:28)
>     at simple_statement (/Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:905:35)
>     at /Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:813:35
>     at /Users/Ben/Node/node-express-boilerplate/node_modules/connect-assetmanager-handlers/node_modules/uglify-js/lib/parse-js.js:1296:32
> 

[]()
inflowing error
