### ISSUE TITLE
Connect-redis

### ISSUE THREAD

**Issue by xandor-io** [mape/node-express-boilerplate#17]
Due to express 4.x.x changes, we now need to pass express-session to the function connect-redis exports in order to extend express-session.Store

**Comment by xandor-io** [comment]
```
Caught exception: TypeError: Cannot read property 'prototype' of undefined
TypeError: Cannot read property 'prototype' of undefined
    at module.exports (/Users/Xandor/git/GoogleMapsApi/node_modules/connect-redis/lib/connect-redis.js:96:41)
    at Object.<anonymous> (/Users/Xandor/git/GoogleMapsApi/server.js:25:42)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```
