### ISSUE TITLE
Twitter auth fails

### ISSUE THREAD

**Issue by vinkaga** [mape/node-express-boilerplate#7]
I am getting the following exception for Twitter based authentication. (Facebook auth works). 

starting step - getRequestToken
Caught exception: Error: Desktop applications only support the oauth_callback value 'oob'
Error: Desktop applications only support the oauth_callback value 'oob'
    at /home/vinay/Projects/nodeapp/node_modules/everyauth/lib/modules/twitter.js:35:12
    at /home/vinay/Projects/nodeapp/node_modules/everyauth/lib/step.js:97:21
    at [object Object].fail (/home/vinay/Projects/nodeapp/node_modules/everyauth/lib/promise.js:53:24)
    at /home/vinay/Projects/nodeapp/node_modules/everyauth/lib/modules/oauth.js:105:18
    at /home/vinay/Projects/nodeapp/node_modules/everyauth/node_modules/oauth/lib/oauth.js:510:17
    at passBackControl (/home/vinay/Projects/nodeapp/node_modules/everyauth/node_modules/oauth/lib/oauth.js:366:13)
    at IncomingMessage.<anonymous> (/home/vinay/Projects/nodeapp/node_modules/everyauth/node_modules/oauth/lib/oauth.js:378:9)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at CleartextStream.ondata (http.js:1231:22)

**Comment by vinkaga** [comment]
It was caused by the application's Twitter settings.

**Comment by christophlsa** [comment]
I have the same error message. Could you tell me what you changed in your settings?

**Comment by christophlsa** [comment]
Oh, I found the solution: You have to enter a callback URL in Application Details on Twitter Developers page (the callback URL do not need match with the real URL).
